displayName=Simple Vitals
author=Podge
description=Keep track of your hiptpoints, prayers, buffs and debuffs!
tags=Vitals,Boosts,Prayers
version=1.0.0
plugins=com.SimpleVitals.SVPlugin
build=standard
